# Generated by Django 3.1.7 on 2021-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='srno',
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone_No',
            field=models.IntegerField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
