# Generated by Django 3.1.7 on 2021-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210401_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_No',
            field=models.IntegerField(default=None),
        ),
    ]
