# Generated by Django 3.1.7 on 2021-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210403_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Proid', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('cat', models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Gymwear', 'Gymwear'), ('Blazers', 'Blazers'), ('Shoes', 'Shoes')], max_length=7)),
                ('subcat', models.CharField(choices=[('CasualShirts', 'Casual Shirt'), ('FormalShirts', 'Formal Shirt'), ('Skinny', 'Skinny'), ('Regular', 'Regular'), ('Slim', 'Slim'), ('CasualShoes', 'Casual Shoes'), ('SportShoes', 'Sport Shoes'), ('FormalShoes', 'Formal Shoes')], max_length=12)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
