# Generated by Django 3.1.7 on 2021-04-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210418_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
